### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Scraayp** [shankypedia/mod-mail-bot#1]
WHERE IS THE ANONYMOUS RESPONSE

**Comment by Scraayp** [comment]
Best first issue

**Comment by pythonmcpi** [comment]
What doesn't work? Please be more specific. Also, what do you need anonymous response for?
If you really need anonymous response and have a good reason I might make a PR

**Comment by SashankBhamidi** [comment]
It is broken.

**Comment by SashankBhamidi** [comment]
Works now
